param(
    [Parameter(Mandatory=$false)]
    [string]$Version
)

$ErrorActionPreference = "Stop"
$pubspec = "pubspec.yaml"

# Read current version from pubspec.yaml
$currentLine = (Select-String -Path $pubspec -Pattern '^version:').Line
$current = ($currentLine -replace 'version: ', '' -replace '\+.*', '').Trim()
$parts = $current.Split('.')
$major = [int]$parts[0]
$minor = [int]$parts[1]
$patch = [int]$parts[2]

# Auto-bump or use provided version
if ([string]::IsNullOrEmpty($Version)) {
    # Auto bump patch: 1.1.3 -> 1.1.4
    $Version = "$major.$minor.$($patch + 1)"
    Write-Host "Auto bump: $current -> $Version"
}
elseif ($Version -eq "minor") {
    # Bump minor: 1.1.3 -> 1.2.0
    $Version = "$major.$($minor + 1).0"
    Write-Host "Bump minor: $current -> $Version"
}
elseif ($Version -eq "major") {
    # Bump major: 1.1.3 -> 2.0.0
    $Version = "$($major + 1).0.0"
    Write-Host "Bump major: $current -> $Version"
}

# Validate semver format
if ($Version -notmatch '^\d+\.\d+\.\d+$') {
    Write-Error "Error: Version must be semver (e.g., 1.1.0)"
    exit 1
}

# Check clean working tree
$status = git status --porcelain
if ($status) {
    Write-Error "Error: Working tree not clean. Commit or stash changes first."
    exit 1
}

# Check tag doesn't exist
$tagCheck = git tag -l "v$Version" 2>&1
if ($tagCheck) {
    Write-Error "Error: Tag v$Version already exists."
    exit 1
}

# Bump version in pubspec.yaml
$oldVersion = (Select-String -Path $pubspec -Pattern '^version:').Line
(Get-Content $pubspec) -replace '^version: .*', "version: $Version+1" | Set-Content $pubspec -Encoding UTF8
Write-Host "Updated $pubspec`: $oldVersion -> version: $Version+1"

# Update version.json
@{version=$Version} | ConvertTo-Json -Compress | Set-Content "assets/version.json" -Encoding UTF8
Write-Host "Updated assets/version.json -> $Version"

# Update Dart const
New-Item -ItemType Directory -Force -Path "lib/generated" | Out-Null
@"
// AUTO-GENERATED by release.sh / CI workflow. DO NOT EDIT manually.
const String appVersion = '$Version';
"@ | Set-Content "lib/generated/version.dart" -Encoding UTF8
Write-Host "Updated lib/generated/version.dart -> $Version"

# Commit, tag, push
git add $pubspec assets/version.json lib/generated/version.dart
git commit -m "release v$Version"
git tag "v$Version"
$branch = git branch --show-current
git push origin $branch --tags

Write-Host ""
Write-Host "Done! v$Version pushed. GitHub Actions will build & release."
Write-Host "Track: https://github.com/namchamvinhcuu/odoo_auto_config/actions"
