#!/bin/bash
set -e

PUBSPEC="pubspec.yaml"

# Read current version from pubspec.yaml
CURRENT=$(grep '^version:' "$PUBSPEC" | head -1 | sed 's/version: //' | sed 's/+.*//')

# Auto-bump or use provided version
if [ -z "$1" ]; then
  # Auto bump patch: 1.1.3 → 1.1.4
  MAJOR=$(echo "$CURRENT" | cut -d. -f1)
  MINOR=$(echo "$CURRENT" | cut -d. -f2)
  PATCH=$(echo "$CURRENT" | cut -d. -f3)
  VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
  echo "Auto bump: $CURRENT → $VERSION"
elif [ "$1" = "minor" ]; then
  # Bump minor: 1.1.3 → 1.2.0
  MAJOR=$(echo "$CURRENT" | cut -d. -f1)
  MINOR=$(echo "$CURRENT" | cut -d. -f2)
  VERSION="$MAJOR.$((MINOR + 1)).0"
  echo "Bump minor: $CURRENT → $VERSION"
elif [ "$1" = "major" ]; then
  # Bump major: 1.1.3 → 2.0.0
  MAJOR=$(echo "$CURRENT" | cut -d. -f1)
  VERSION="$((MAJOR + 1)).0.0"
  echo "Bump major: $CURRENT → $VERSION"
else
  VERSION="$1"
fi

# Validate semver format
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "Error: Version must be semver (e.g., 1.1.0)"
  exit 1
fi

# Check clean working tree
if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Working tree not clean. Commit or stash changes first."
  exit 1
fi

# Check tag doesn't exist
if git rev-parse "v$VERSION" >/dev/null 2>&1; then
  echo "Error: Tag v$VERSION already exists."
  exit 1
fi

# Bump version in pubspec.yaml
OLD_VERSION=$(grep '^version:' "$PUBSPEC" | head -1)
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/^version: .*/version: $VERSION+1/" "$PUBSPEC"
else
  sed -i "s/^version: .*/version: $VERSION+1/" "$PUBSPEC"
fi
echo "Updated $PUBSPEC: $OLD_VERSION → version: $VERSION+1"

# Update version.json
echo "{\"version\": \"$VERSION\"}" > assets/version.json
echo "Updated assets/version.json → $VERSION"

# Update Dart const
mkdir -p lib/generated
cat > lib/generated/version.dart <<EOF
// AUTO-GENERATED by release.sh / CI workflow. DO NOT EDIT manually.
const String appVersion = '$VERSION';
EOF
echo "Updated lib/generated/version.dart → $VERSION"

# Commit, tag, push
git add "$PUBSPEC" assets/version.json lib/generated/version.dart
git commit -m "release v$VERSION"
git tag "v$VERSION"
git push origin "$(git branch --show-current)" --tags

echo ""
echo "Done! v$VERSION pushed. GitHub Actions will build & release."
echo "Track: https://github.com/namchamvinhcuu/odoo_auto_config/actions"
