import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:odoo_auto_config/services/platform_service.dart';

/// Resolved command to launch an Odoo server — mirrors the VSCode "F5" debug
/// config generated by [VscodeConfigService]: `python odoo-bin -c odoo.conf --dev xml`.
class OdooLaunchConfig {
  /// Absolute path to the Python interpreter (from launch.json or venv fallback).
  final String? python;

  /// Absolute path to `odoo-bin`.
  final String? odooBin;

  /// Arguments passed to odoo-bin (already `${workspaceFolder}`-resolved).
  final List<String> args;

  /// Resolved path to `odoo.conf`, if any.
  final String? confPath;

  /// HTTP port the server listens on (from `--http-port` arg or `odoo.conf`).
  /// Used to detect readiness by polling the port — robust against a high
  /// `log_level` that suppresses the "HTTP service running" log line.
  final int? httpPort;

  /// Working directory to spawn the process in (the project root).
  final String workingDirectory;

  const OdooLaunchConfig({
    this.python,
    this.odooBin,
    this.args = const [],
    this.confPath,
    this.httpPort,
    required this.workingDirectory,
  });

  /// True when both interpreter and odoo-bin were resolved — enough to spawn.
  bool get isRunnable =>
      python != null &&
      python!.isNotEmpty &&
      odooBin != null &&
      odooBin!.isNotEmpty;
}

/// Reads `.vscode/launch.json` to resolve the Python interpreter + odoo-bin +
/// args used to run an Odoo project, with sensible fallbacks.
///
/// Single source of truth for launch resolution — used by both the project
/// info dialog and the workspace "run server" feature.
class OdooLaunchConfigService {
  static Future<OdooLaunchConfig> resolve(String projectPath) async {
    String? python;
    String? odooBin;
    String? confPath;
    List<String> args = const [];

    // Primary source: .vscode/launch.json (matches VscodeConfigService.generate).
    final launchFile = File(p.join(projectPath, '.vscode', 'launch.json'));
    if (await launchFile.exists()) {
      try {
        final json =
            jsonDecode(await launchFile.readAsString()) as Map<String, dynamic>;
        final configs = json['configurations'] as List?;
        if (configs != null && configs.isNotEmpty) {
          final config = configs.first as Map<String, dynamic>;
          python = config['python']?.toString();
          final program = config['program']?.toString();
          if (program != null) {
            odooBin = _resolveWorkspace(program, projectPath);
          }
          final rawArgs = config['args'] as List?;
          if (rawArgs != null) {
            args = rawArgs
                .map((a) => _resolveWorkspace(a.toString(), projectPath))
                .toList();
          }
        }
      } catch (_) {
        // Malformed launch.json → fall through to fallbacks below.
      }
    }

    // Fallbacks when launch.json is missing / incomplete.
    odooBin ??= await _firstExisting([
      p.join(projectPath, 'odoo', 'odoo-bin'),
      p.join(projectPath, 'odoo-bin'),
    ]);
    python ??= await _firstExisting([
      PlatformService.venvPython(p.join(projectPath, 'venv')),
      PlatformService.venvPython(p.join(projectPath, '.venv')),
    ]);

    // Config path: prefer `-c <conf>` from args, else common locations.
    confPath = _confFromArgs(args) ??
        await _firstExisting([
          p.join(projectPath, 'odoo.conf'),
          p.join(projectPath, 'config', 'odoo.conf'),
        ]);

    // Synthesize a minimal command when launch.json gave no args.
    if (args.isEmpty && confPath != null) {
      args = ['-c', confPath, '--dev', 'xml'];
    }

    // HTTP port: explicit --http-port arg wins, else read from odoo.conf.
    final httpPort =
        _httpPortFromArgs(args) ?? await _httpPortFromConf(confPath);

    return OdooLaunchConfig(
      python: python,
      odooBin: odooBin,
      args: args,
      confPath: confPath,
      httpPort: httpPort,
      workingDirectory: projectPath,
    );
  }

  static int? _httpPortFromArgs(List<String> args) {
    for (var i = 0; i < args.length - 1; i++) {
      if (args[i] == '--http-port' || args[i] == '-p') {
        return int.tryParse(args[i + 1]);
      }
    }
    return null;
  }

  static Future<int?> _httpPortFromConf(String? confPath) async {
    if (confPath == null) return null;
    try {
      final content = await File(confPath).readAsString();
      final m = RegExp(r'^\s*http_port\s*=\s*(\d+)', multiLine: true)
          .firstMatch(content);
      if (m != null) return int.tryParse(m.group(1)!);
    } catch (_) {}
    return null;
  }

  static String _resolveWorkspace(String value, String projectPath) =>
      value.replaceAll(r'${workspaceFolder}', projectPath);

  static String? _confFromArgs(List<String> args) {
    for (var i = 0; i < args.length - 1; i++) {
      if (args[i] == '-c' || args[i] == '--config') return args[i + 1];
    }
    return null;
  }

  static Future<String?> _firstExisting(List<String> candidates) async {
    for (final c in candidates) {
      if (await File(c).exists()) return c;
    }
    return null;
  }
}
