import 'dart:math';
import 'package:path/path.dart' as p;

class OdooTemplates {
  static String odooConf({
    required int httpPort,
    required int longpollingPort,
    required String projectPath,
    required String filestorePath,
    String dbHost = 'localhost',
    int dbPort = 5432,
    String dbUser = 'odoo',
    String dbPassword = '',
    String dbSslmode = 'prefer',
  }) {
    final adminPasswd = _generatePassword(16);
    final effectiveDbPassword =
        dbPassword.isEmpty ? _generatePassword(48) : dbPassword;

    return '''[options]
addons_path = ./addons,./odoo/addons
admin_passwd = $adminPasswd
http_port = $httpPort
longpolling_port = $longpollingPort
# xmlrpc_port = 8069
dbfilter = ^%d\$
csv_internal_sep = ,
data_dir = $filestorePath
db_host = $dbHost
db_maxconn = 64
db_name = False
db_user = $dbUser
db_password = $effectiveDbPassword
db_port = $dbPort
db_sslmode = $dbSslmode
db_template = template0
demo = {}
email_from = False
from_filter = False
http_enable = True
http_interface =
import_partial =
limit_memory_hard = 10737418240
limit_memory_soft = 10737418240
limit_request = 0
limit_time_cpu = 86400
limit_time_real = 86400
list_db = True
log_db = False
log_db_level = warning
log_handler = :WARN
log_level = error
; logfile = ./odoo.log
osv_memory_age_limit = False
osv_memory_count_limit = False
pidfile =
proxy_mode = True
reportgz = False
screencasts =
screenshots = ${p.join(projectPath, 'screenshots')}
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_ssl_certificate_filename = False
smtp_ssl_private_key_filename = False
smtp_user = False
syslog = False
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path =
without_demo = False
; workers = None
max_file_size = 0
http_socket_timeout = 3600
web.max_file_upload_size = 1073741824
document.max_fileupload_size = 1073741824
''';
  }

  static String _generatePassword(int length) {
    const chars =
        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    final rng = Random.secure();
    return List.generate(length, (_) => chars[rng.nextInt(chars.length)])
        .join();
  }

  static String readme({
    required String projectName,
    required int odooVersion,
    required int httpPort,
  }) {
    return '''# $projectName - Odoo $odooVersion Development

## Project Structure

```
$projectName/
  odoo/                     # Symlink to Odoo source code
  addons/                   # Custom modules
  third_party_addons/       # OCA / community modules
  odoo.conf                 # Odoo configuration
  filestore/                # Odoo filestore
```

## Run Odoo

```bash
python odoo/odoo-bin -c odoo.conf
```

Access at http://localhost:$httpPort

## Development

Place your custom modules in `addons/` and community modules in `third_party_addons/`.

Generated by **Odoo Auto Config**
''';
  }
}
