import 'dart:math';
import 'package:path/path.dart' as p;

class OdooTemplates {
  static String odooConf({
    required int httpPort,
    required int longpollingPort,
    required String projectPath,
    required String filestorePath,
    String dbHost = 'localhost',
    int dbPort = 5432,
    String dbUser = 'odoo',
    String dbPassword = '',
    String dbSslmode = 'prefer',
  }) {
    final adminPasswd = _generatePassword(16);
    final effectiveDbPassword =
        dbPassword.isEmpty ? _generatePassword(48) : dbPassword;

    return '''[options]
addons_path = ./addons,./odoo/addons
admin_passwd = $adminPasswd
http_port = $httpPort
longpolling_port = $longpollingPort
# xmlrpc_port = 8069
dbfilter = ^.*\$
csv_internal_sep = ,
data_dir = $filestorePath
db_host = $dbHost
db_maxconn = 64
db_name = False
db_user = $dbUser
db_password = $effectiveDbPassword
db_port = $dbPort
db_sslmode = $dbSslmode
db_template = template0
demo = {}
email_from = False
from_filter = False
http_enable = True
http_interface =
import_partial =
limit_memory_hard = 10737418240
limit_memory_soft = 10737418240
limit_request = 0
limit_time_cpu = 86400
limit_time_real = 86400
list_db = True
log_db = False
log_db_level = warning
log_handler = :WARN
log_level = error
; logfile = ./odoo.log
osv_memory_age_limit = False
osv_memory_count_limit = False
pidfile =
proxy_mode = True
reportgz = False
screencasts =
screenshots = ${p.join(projectPath, 'screenshots')}
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_ssl_certificate_filename = False
smtp_ssl_private_key_filename = False
smtp_user = False
syslog = False
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path =
without_demo = False
; workers = None
max_file_size = 0
http_socket_timeout = 3600
web.max_file_upload_size = 1073741824
document.max_fileupload_size = 1073741824
''';
  }

  static String _generatePassword(int length) {
    const chars =
        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    final rng = Random.secure();
    return List.generate(length, (_) => chars[rng.nextInt(chars.length)])
        .join();
  }

  static String readme({
    required String projectName,
    required int odooVersion,
    required int httpPort,
  }) {
    return '''# $projectName - Odoo $odooVersion Development

## Project Structure

```
$projectName/
  odoo/                     # Symlink to Odoo source code
  addons/                   # Custom modules
  third_party_addons/       # OCA / community modules
  odoo.conf                 # Odoo configuration
  filestore/                # Odoo filestore
```

## Run Odoo

```bash
python odoo/odoo-bin -c odoo.conf
```

Access at http://localhost:$httpPort

## Development

Place your custom modules in `addons/` and community modules in `third_party_addons/`.

Generated by **Odoo Auto Config**
''';
  }

  static String gitRepositoriesSh({String token = '', String org = ''}) {
    final effectiveToken = token.isEmpty ? 'YOUR_GITHUB_TOKEN' : token;
    final effectiveOrg = org.isEmpty ? 'YOUR_ORGANIZATION' : org;
    return '#!/bin/bash\n'
        '# ----------------- Config -----------------\n'
        'TOKEN="$effectiveToken"\n'
        'ORG_NAME="$effectiveOrg"\n'
        r'''
CURRENT_DIR=$(pwd)
ADDONS_DIR="$CURRENT_DIR/addons"
IGNORE_LIST_PATH="$CURRENT_DIR/ignore_repos.txt"

# Colors
LIGHT_GRAY='\033[0;90m'
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="\033[0;94m"
RESET="\033[0m"

MODULES_INSTALL=()
MODULES_UPGRADE=()
MODULES_IGNORE=()
MODULES_ERROR=()

# ========== Helpers ==========
log() {
    local message="$1"
    echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] $message"
}

is_ignored() {
    local REPO_NAME="$1"
    [[ -f "$IGNORE_LIST_PATH" ]] && grep -Fxq "$REPO_NAME" "$IGNORE_LIST_PATH"
}

clone_or_update_repo() {
    local REPO="$1"
    local REPO_NAME=$(basename "$REPO" .git)

    if is_ignored "$REPO_NAME"; then
        log "${LIGHT_GRAY}Ignoring repo $REPO_NAME${RESET}"
        MODULES_IGNORE+=("$REPO_NAME")
        return 0
    fi

    if [[ -d "$REPO_NAME" ]]; then
        log "Pulling latest changes for $REPO_NAME..."
        local pull_output
        pull_output=$(cd "$REPO_NAME" && git pull 2>&1)
        local pull_exit_code=$?

        if [[ $pull_exit_code -ne 0 ]]; then
            log "${RED}Pull failed for $REPO_NAME${RESET}"
            MODULES_ERROR+=("$REPO_NAME")
        elif echo "$pull_output" | grep -qE "Already up to date|Already up-to-date"; then
            log "No changes for $REPO_NAME"
        else
            log "${YELLOW}Updated repo $REPO_NAME${RESET}"
            MODULES_UPGRADE+=("$REPO_NAME")
        fi
    else
        log "${BLUE}Cloning $REPO_NAME...${RESET}"
        if git clone "$REPO" 2>&1; then
            log "${GREEN}Successfully cloned $REPO_NAME${RESET}"
            MODULES_INSTALL+=("$REPO_NAME")
        else
            log "${RED}Failed to clone $REPO_NAME${RESET}"
            MODULES_ERROR+=("$REPO_NAME")
        fi
    fi
    return 0
}

# ========== Core ==========
process_modules() {
    mkdir -p "$ADDONS_DIR"

    pushd "$ADDONS_DIR" >/dev/null || {
        log "${RED}Cannot access $ADDONS_DIR${RESET}"
        exit 1
    }

    local PAGE=1
    while :; do
        RESPONSE=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100&page=$PAGE")

        if echo "$RESPONSE" | jq -e '.message' >/dev/null 2>&1; then
            log "${RED}API Error: $(echo "$RESPONSE" | jq -r '.message')${RESET}"
            break
        fi

        REPOS=$(echo "$RESPONSE" | jq -r '.[].clone_url' 2>/dev/null)
        [[ -z "$REPOS" ]] && break

        for REPO in $REPOS; do
            clone_or_update_repo "$REPO"
        done
        PAGE=$((PAGE + 1))
    done

    popd >/dev/null || exit
}

show_summary() {
    local install=$(IFS=,; echo "${MODULES_INSTALL[*]}")
    local upgrade=$(IFS=,; echo "${MODULES_UPGRADE[*]}")
    local error=$(IFS=,; echo "${MODULES_ERROR[*]}")
    local ignore=$(IFS=,; echo "${MODULES_IGNORE[*]}")

    log "${GREEN}========== SUMMARY ==========${RESET}"
    log "${BLUE}INSTALL: ${RESET}${install:-None}"
    log "${YELLOW}UPGRADE: ${RESET}${upgrade:-None}"
    log "${RED}ERROR: ${RESET}${error:-None}"
    log "${LIGHT_GRAY}IGNORED: ${RESET}${ignore:-None}"
    log "${GREEN}========== END OF SUMMARY ==========${RESET}"
}

# ========== Main ==========
main() {
    if ! command -v jq &>/dev/null; then
        log "${RED}jq is not installed. Please install it first.${RESET}"
        exit 1
    fi

    if [[ "$TOKEN" == "YOUR_GITHUB_TOKEN" ]] || [[ -z "$TOKEN" ]]; then
        log "${RED}Please set your GitHub TOKEN in this script${RESET}"
        exit 1
    fi

    if [[ "$ORG_NAME" == "YOUR_ORGANIZATION" ]] || [[ -z "$ORG_NAME" ]]; then
        log "${RED}Please set your ORG_NAME in this script${RESET}"
        exit 1
    fi

    log "${GREEN}Starting sync for organization: $ORG_NAME${RESET}"
    process_modules
    show_summary
}

main "$@"
''';
  }

  static String gitRepositoriesPs1({String token = '', String org = ''}) {
    final effectiveToken = token.isEmpty ? 'YOUR_GITHUB_TOKEN' : token;
    final effectiveOrg = org.isEmpty ? 'YOUR_ORGANIZATION' : org;
    return '# ----------------- Config -----------------\n'
        '\$TOKEN = "$effectiveToken"\n'
        '\$ORG_NAME = "$effectiveOrg"\n'
        r'''
$CURRENT_DIR = Get-Location
$ADDONS_DIR = Join-Path $CURRENT_DIR "addons"
$IGNORE_LIST_PATH = Join-Path $CURRENT_DIR "ignore_repos.txt"

$MODULES_INSTALL = @()
$MODULES_UPGRADE = @()
$MODULES_IGNORE = @()
$MODULES_ERROR = @()

# ========== Helpers ==========
function Log($message) {
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] $message"
}

function Is-Ignored($repoName) {
    if (Test-Path $IGNORE_LIST_PATH) {
        $lines = Get-Content $IGNORE_LIST_PATH | Where-Object { $_.Trim() -ne "" }
        return $lines -contains $repoName
    }
    return $false
}

function Clone-Or-Update-Repo($repoUrl) {
    $repoName = [System.IO.Path]::GetFileNameWithoutExtension($repoUrl)

    if (Is-Ignored $repoName) {
        Log "`e[90mIgnoring repo $repoName`e[0m"
        $script:MODULES_IGNORE += $repoName
        return
    }

    $repoPath = Join-Path $ADDONS_DIR $repoName

    if (Test-Path $repoPath) {
        Log "Pulling latest changes for $repoName..."
        Push-Location $repoPath
        try {
            $pullOutput = git pull 2>&1 | Out-String
            $exitCode = $LASTEXITCODE

            if ($exitCode -ne 0) {
                Log "`e[31mPull failed for $repoName`e[0m"
                $script:MODULES_ERROR += $repoName
            }
            elseif ($pullOutput -match "Already up to date|Already up-to-date") {
                Log "No changes for $repoName"
            }
            else {
                Log "`e[33mUpdated repo $repoName`e[0m"
                $script:MODULES_UPGRADE += $repoName
            }
        }
        finally {
            Pop-Location
        }
    }
    else {
        Log "`e[94mCloning $repoName...`e[0m"
        git clone $repoUrl $repoPath 2>&1 | Out-String | Write-Host
        if ($LASTEXITCODE -eq 0) {
            Log "`e[32mSuccessfully cloned $repoName`e[0m"
            $script:MODULES_INSTALL += $repoName
        }
        else {
            Log "`e[31mFailed to clone $repoName`e[0m"
            $script:MODULES_ERROR += $repoName
        }
    }
}

# ========== Core ==========
function Process-Modules {
    if (-not (Test-Path $ADDONS_DIR)) {
        New-Item -ItemType Directory -Path $ADDONS_DIR -Force | Out-Null
    }

    $page = 1
    $headers = @{ Authorization = "token $TOKEN"; Accept = "application/vnd.github.v3+json" }

    while ($true) {
        $url = "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100&page=$page"
        try {
            $response = Invoke-RestMethod -Uri $url -Headers $headers -ErrorAction Stop
        }
        catch {
            Log "`e[31mAPI Error: $($_.Exception.Message)`e[0m"
            break
        }

        if ($response.Count -eq 0) { break }

        foreach ($repo in $response) {
            Clone-Or-Update-Repo $repo.clone_url
        }
        $page++
    }
}

function Show-Summary {
    $install = if ($MODULES_INSTALL.Count -gt 0) { $MODULES_INSTALL -join "," } else { "None" }
    $upgrade = if ($MODULES_UPGRADE.Count -gt 0) { $MODULES_UPGRADE -join "," } else { "None" }
    $error   = if ($MODULES_ERROR.Count -gt 0)   { $MODULES_ERROR -join "," }   else { "None" }
    $ignore  = if ($MODULES_IGNORE.Count -gt 0)  { $MODULES_IGNORE -join "," }  else { "None" }

    Log "`e[32m========== SUMMARY ==========`e[0m"
    Log "`e[94mINSTALL: `e[0m$install"
    Log "`e[33mUPGRADE: `e[0m$upgrade"
    Log "`e[31mERROR:   `e[0m$error"
    Log "`e[90mIGNORED: `e[0m$ignore"
    Log "`e[32m========== END OF SUMMARY ==========`e[0m"
}

# ========== Main ==========
function Main {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Log "`e[31mgit is not installed. Please install it first.`e[0m"
        exit 1
    }

    if ($TOKEN -eq "YOUR_GITHUB_TOKEN" -or [string]::IsNullOrEmpty($TOKEN)) {
        Log "`e[31mPlease set your GitHub TOKEN in this script`e[0m"
        exit 1
    }

    if ($ORG_NAME -eq "YOUR_ORGANIZATION" -or [string]::IsNullOrEmpty($ORG_NAME)) {
        Log "`e[31mPlease set your ORG_NAME in this script`e[0m"
        exit 1
    }

    Log "`e[32mStarting sync for organization: $ORG_NAME`e[0m"
    Process-Modules
    Show-Summary
}

Main
''';
  }
}
