class PostgresTemplates {
  static String dockerCompose() {
    return r'''services:
  postgres_db:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - ${PORT}
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
''';
  }

  static String envFile({
    required String user,
    required String password,
    required int hostPort,
  }) {
    return '''IMAGE=postgres:16-alpine
CONTAINER_NAME=postgres_db

POSTGRES_DB=postgres
POSTGRES_USER=$user
POSTGRES_PASSWORD=$password
PORT=$hostPort:5432
''';
  }

  static String postgresqlConf() {
    return r"""# PostgreSQL configuration for development
# Generated by Workspace Configuration

#------------------------------------------------------------------------------
# CONNECTIONS AND AUTHENTICATION
#------------------------------------------------------------------------------

listen_addresses = '*'
#port = 5432
max_connections = 100

#------------------------------------------------------------------------------
# RESOURCE USAGE
#------------------------------------------------------------------------------

shared_buffers = 128MB
dynamic_shared_memory_type = posix
#work_mem = 4MB
#maintenance_work_mem = 64MB

#------------------------------------------------------------------------------
# WRITE-AHEAD LOG
#------------------------------------------------------------------------------

max_wal_size = 1GB
min_wal_size = 80MB

#------------------------------------------------------------------------------
# REPORTING AND LOGGING
#------------------------------------------------------------------------------

log_timezone = 'Etc/UTC'

#------------------------------------------------------------------------------
# CLIENT CONNECTION DEFAULTS
#------------------------------------------------------------------------------

datestyle = 'iso, mdy'
timezone = 'Etc/UTC'

lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'

default_text_search_config = 'pg_catalog.english'
""";
  }
}
